name:
  maximum: 50
email:
  maximum: 255
password:
  minimum: 6
gravatar:
  size_80: 80
remember_me: "1"
expired:
  password_reset: 2
product_name:
  maximum: 255
  minimum: 5
product_information:
  maximum: 4095
  minimum: 20
  truncate: 111
product_price:
  minimum: 0
product_quantity:
  minimum: 0
per_page: 15
per_page:
  products: 12
carts:
  minimum_quantity: 1
  default_quantity: 1
  no_product: 0
filter:
  minimum_price: "0"
